import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar/Navbar";
import AuthProvider from "../context/AuthContext"
import { Toaster } from "sonner";

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${outfit.className} h-full`}>
      <body className="min-h-full flex flex-col">
        <AuthProvider>
        <Navbar />
        {children}
           <Toaster />
        </AuthProvider>
      </body>
    </html>
  );
}
